name: Build and Deploy Check

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (Prod Mode Simulation)
        run: pnpm --frozen-lockfile install --prod

      - name: Build
        run: pnpm build:only

      - name: Feedback
        run: echo "Build check passed"
