name: Format and Lint Check

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (Normal Mode)
        run: pnpm install

      - name: Format Check with Prettier
        run: pnpm format:check

      - name: Lint Check with ESLint
        run: pnpm lint

      - name: Feedback
        run: echo "Formatting and linting check passed"
